package be.mbolle.wordytony.ui

import androidx.lifecycle.ViewModel
import be.mbolle.wordytony.data.words

class WordFinderViewModel(): ViewModel() {


    private val usedWords: Set<String> = mutableSetOf()
    private val width: Int = 5
    private val height = 8
    var terrain: Array<Array<Char>> = Array(width) { Array(height) { ' ' } }
        private set


    init {
        initSearchableWord(width, height)
    }

    /**
     * Places the generated word from in a index-based grid.
     * This grid is further generated by
     */
    fun initSearchableWord(width: Int, height: Int) {
        val chosenWord = words.random()
        val directionOfWord = getDirectionFromWord(chosenWord, width, height)

        val widthIndex = width - 1
        val heightIndex = height - 1

        when (directionOfWord) {

            Direction.WIDTH -> {
                // generate a random value between 0 (index) and (width-1) where 0+length of word
                var validEndIndexes: Array<Int> = IntArray(width) { it + 1 }.toTypedArray()

                validEndIndexes = validEndIndexes.filter { index ->
                    index + (chosenWord.length - 1) > widthIndex
                }.toTypedArray()

                val validEndIndex = validEndIndexes.random()

                val widthIndexes = validIndexesOfWord(chosenWord, validEndIndex)

                val constantHeight = (0..heightIndex).random()

                widthIndexes.forEachIndexed { index, element ->
                    terrain[element][constantHeight] = chosenWord[index]
                }

                terrain = fillUpEmptySpots(terrain)
            }

            Direction.WIDTH_HEIGHT -> {

            }


            Direction.HEIGHT -> {

            }

            Direction.INVALID -> {

            }
        }
    }

    private fun validIndexesOfWord(word: String, endIndex: Int): Array<Int> {
        var theIndex: Int
        val indexes : Array<Int> = word.map {
            theIndex = endIndex - 1
            return@map theIndex + 1
        }.toTypedArray()

        return indexes
    }

    fun fillUpEmptySpots(terrain: Array<Array<Char>>): Array<Array<Char>> {
        return terrain.map {
            element -> element.map {
                nextElement -> if (nextElement == ' ') ('A'..'Z').random() else nextElement
            }.toTypedArray()
        }.toTypedArray()
    }

    private fun getDirectionFromWord(word: String, width: Int, height: Int): Direction {
        if (word.length > width && word.length > height) {
            return Direction.INVALID
        }
        if (word.length <= width) {
            if (word.length <= height) {
                return Direction.WIDTH_HEIGHT
            }
            return Direction.WIDTH
        }
        return Direction.HEIGHT
    }
}

/**
 * The possible directions that a word can be placed on the screen.
 */
enum class Direction {
    WIDTH, HEIGHT, WIDTH_HEIGHT, INVALID
}